title: My BugBounty Journal
description: The journal of a unix geek taking its first steps into the BugBounty world...
show_downloads: false
remote_theme: pages-themes/hacker@v0.2.0
google_analytics:
github:
  is_project_page: false
plugins:
- jekyll-remote-theme
- jemoji
author:
  twitter: PantelisRoditis
defaults:
  - scope:
      path: ""
    values:
      image: https://repository-images.githubusercontent.com/571153544/6eee7f75-677c-4efb-9c20-778c8ed13f2a
